pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.WindowManager

Singleton {
    id: root

    readonly property string name: {
        if (Quickshell.env("HYPRLAND_INSTANCE_SIGNATURE"))
            return "hyprland";
        if (Quickshell.env("NIRI_SOCKET"))
            return "niri";
        if (Quickshell.env("SWAYSOCK"))
            return "sway";
        return "unknown";
    }

    readonly property string displayName: ({
        hyprland: "Hyprland",
        niri: "Niri",
        sway: "Sway"
    }[name] ?? "Unknown compositor")

    readonly property list<Windowset> workspaces: {
        const sets = WindowManager.windowsets.filter(w => w.shouldDisplay);
        return sets.sort((a, b) => {
            const ca = a.coordinates, cb = b.coordinates;
            if (ca.length && cb.length)
                return ca[0] - cb[0];
            const na = parseInt(a.name), nb = parseInt(b.name);
            if (!isNaN(na) && !isNaN(nb))
                return na - nb;
            return a.name.localeCompare(b.name);
        });
    }

    readonly property Windowset activeWorkspace: workspaces.find(w => w.active) ?? null

    function workspacesFor(screen: ShellScreen): var {
        const scoped = workspaces.filter(w => w.projection?.screens.includes(screen));
        return scoped.length > 0 ? scoped : workspaces;
    }

    readonly property ShellScreen focusedScreen: activeWorkspace?.projection?.screens[0] ?? Quickshell.screens[0] ?? null

    function label(workspace: Windowset): string {
        if (!workspace)
            return "";
        if (workspace.name)
            return workspace.name.replace(/^special:/, "");
        const coords = workspace.coordinates;
        return coords.length > 0 ? String(coords[coords.length - 1]) : "\u2022";
    }

    function activate(workspace: Windowset): void {
        if (workspace?.canActivate)
            workspace.activate();
    }

    readonly property var logoutCommand: ({
        hyprland: ["hyprctl", "dispatch", "exit"],
        sway: ["swaymsg", "exit"],
        niri: ["niri", "msg", "action", "quit", "--skip-confirmation"]
    }[name] ?? ["loginctl", "terminate-session", Quickshell.env("XDG_SESSION_ID") ?? ""])

    readonly property list<string> lockCommand: ["loginctl", "lock-session"]

    readonly property string defaultOutputConfigPath: ({
        hyprland: "~/.config/hypr/monitors.conf",
        sway: "~/.config/sway/outputs",
        niri: "~/.config/niri/outputs.kdl"
    }[name] ?? "")

    readonly property string outputConfigHint: ({
        hyprland: "source = <path>",
        sway: "include <path>",
        niri: "// niri has no include directive - paste this into config.kdl"
    }[name] ?? "")

    readonly property var transforms: ["normal", "90", "180", "270", "flipped", "flipped-90", "flipped-180", "flipped-270"]

    function renderOutputConfig(outputs: var): string {
        const lines = [`# Generated by basedgoose.shell for ${root.displayName}`, ""];
        for (const output of outputs)
            lines.push(_renderOutput(output));
        return lines.join("\n") + "\n";
    }

    function _renderOutput(o: var): string {
        const mode = `${o.width}x${o.height}@${o.refresh % 1 === 0 ? o.refresh : o.refresh.toFixed(3)}`;
        const rotated = o.transform && o.transform !== "normal";

        switch (root.name) {
        case "hyprland":
            if (!o.enabled)
                return `monitor = ${o.name}, disable`;
            return [`monitor = ${o.name}, ${mode}Hz, ${o.x}x${o.y}, ${o.scale}`,
                    rotated ? `, transform, ${transforms.indexOf(o.transform)}` : "",
                    o.mirror ? `, mirror, ${o.mirror}` : ""].join("");
        case "niri":
            if (!o.enabled)
                return `output "${o.name}" { off }`;
            return [`output "${o.name}" {`,
                    `    mode "${mode}"`,
                    `    position x=${o.x} y=${o.y}`,
                    `    scale ${o.scale}`,
                    rotated ? `    transform "${o.transform}"` : "",
                    "}"].filter(line => line).join("\n");
        default:
            if (!o.enabled)
                return `output ${o.name} disable`;
            return `output ${o.name} mode ${mode}Hz position ${o.x} ${o.y} scale ${o.scale}` + (rotated ? ` transform ${o.transform}` : "");
        }
    }

    function reloadConfig(): void {
        const cmd = ({
            hyprland: ["hyprctl", "reload"],
            sway: ["swaymsg", "reload"]
        })[root.name];
        if (cmd)
            reloader.exec(cmd);
    }

    Process {
        id: reloader
    }
}
